---
plugin: google.cloud.gcp_compute
projects:
  - monitoring-477616
auth_kind: serviceaccount

hostnames:
  - private_ip

keyed_groups:
  - key: labels.role
    prefix: gcp_role

compose:
  monitoring_servers: "labels.role == 'monitoring'"
  ansible_host: private_ip